version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5001:80"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
